import * as fs from 'fs/promises';
import * as path from 'path';

export interface DocGenerationOptions {
  targetFile: string;
  format?: 'markdown' | 'html';
  includeExamples?: boolean;
  includeTypeSignatures?: boolean;
}

export class DocGenerator {
  async generateDocumentation(options: DocGenerationOptions): Promise<string> {
    const content = await fs.readFile(options.targetFile, 'utf-8');
    const fileName = path.basename(options.targetFile);

    let docs = this.generateHeader(fileName, options);

    // Extract and document functions
    const functions = this.extractFunctionsWithDetails(content);
    if (functions.length > 0) {
      docs += this.generateFunctionSection(functions, options);
    }

    // Extract and document classes
    const classes = this.extractClassesWithDetails(content);
    if (classes.length > 0) {
      docs += this.generateClassSection(classes, options);
    }

    return docs;
  }

  private generateHeader(fileName: string, options: DocGenerationOptions): string {
    if (options.format === 'html') {
      return `<h1>Documentation for ${fileName}</h1>
`;
    }
    return `# Documentation for ${fileName}

> Auto-generated by Ourin Autonomy Tool

---

`;
  }

  private extractFunctionsWithDetails(content: string): Array<{
    name: string;
    signature: string;
    comment?: string;
  }> {
    const functions: Array<{ name: string; signature: string; comment?: string }> = [];

    // Find function definitions with preceding comments
    const lines = content.split('\n');
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const funcMatch = line.match(/func\s+(\w+)\s*\(([^)]*)\)\s*(->\s*.+)?/);

      if (funcMatch) {
        const funcName = funcMatch[1];
        const signature = line.trim();

        // Look for preceding comment
        let comment: string | undefined;
        let j = i - 1;
        while (j >= 0 && (lines[j].trim().startsWith('//') || lines[j].trim().startsWith('/*'))) {
          comment = (comment || '') + lines[j].trim() + '\n';
          j--;
        }

        functions.push({ name: funcName, signature, comment: comment?.trim() });
      }
    }

    return functions;
  }

  private extractClassesWithDetails(content: string): Array<{
    name: string;
    type: string;
    comment?: string;
  }> {
    const classes: Array<{ name: string; type: string; comment?: string }> = [];

    const classPattern = /(class|struct|enum)\s+(\w+)/g;
    let match;
    while ((match = classPattern.exec(content)) !== null) {
      classes.push({ name: match[2], type: match[1] });
    }

    return classes;
  }

  private generateFunctionSection(functions: any[], options: DocGenerationOptions): string {
    let section = options.format === 'html' ? '<h2>Functions</h2>\n' : '## Functions\n\n';

    for (const func of functions) {
      if (options.format === 'html') {
        section += `<h3>${func.name}</h3>\n`;
        if (func.comment) {
          section += `<p>${func.comment.replace(/\n/g, '<br>')}</p>\n`;
        }
        if (options.includeTypeSignatures) {
          section += `<pre><code>${func.signature}</code></pre>\n`;
        }
      } else {
        section += `### ${func.name}\n\n`;
        if (func.comment) {
          section += `${func.comment}\n\n`;
        }
        if (options.includeTypeSignatures) {
          section += '```swift\n' + func.signature + '\n```\n\n';
        }
        if (options.includeExamples) {
          section += '**Usage Example:**\n\n```swift\n// TODO: Add example\n```\n\n';
        }
      }
    }

    return section;
  }

  private generateClassSection(classes: any[], options: DocGenerationOptions): string {
    let section = options.format === 'html' ? '<h2>Types</h2>\n' : '## Types\n\n';

    for (const cls of classes) {
      if (options.format === 'html') {
        section += `<h3>${cls.type} ${cls.name}</h3>\n`;
      } else {
        section += `### ${cls.type} ${cls.name}\n\n`;
      }
      if (options.includeExamples) {
        section += '**Usage Example:**\n\n```swift\n// TODO: Add example\n```\n\n';
      }
    }

    return section;
  }

  async generateMarkdownReport(analysis: any): Promise<string> {
    let report = `# Ourin Project Analysis Report

> Generated on ${new Date().toISOString()}

## Summary

- **Total Files:** ${analysis.summary.totalFiles}
- **Total Lines of Code:** ${analysis.summary.totalLOC}
- **Average Complexity:** ${analysis.summary.avgComplexity.toFixed(2)}
- **Total Issues:** ${analysis.summary.totalIssues}
  - Errors: ${analysis.summary.errors}
  - Warnings: ${analysis.summary.warnings}

## Recommendations

`;

    analysis.recommendations.forEach((rec: string, i: number) => {
      report += `${i + 1}. ${rec}\n`;
    });

    report += '\n## Files with Issues\n\n';

    for (const file of analysis.files) {
      if (file.issues.length > 0) {
        report += `### ${path.basename(file.file)}\n\n`;
        report += `- Lines of Code: ${file.linesOfCode}\n`;
        report += `- Complexity: ${file.complexity}\n`;
        report += `- Functions: ${file.functions}\n`;
        report += `- Issues: ${file.issues.length}\n\n`;

        for (const issue of file.issues) {
          const icon = issue.severity === 'error' ? '❌' : issue.severity === 'warning' ? '⚠️' : 'ℹ️';
          report += `  ${icon} Line ${issue.line}: ${issue.message}\n`;
        }
        report += '\n';
      }
    }

    return report;
  }
}
